layout_spectrum: 0.914841
typography_spectrum: 0.7543281
color:
  saturation: 0.3750702
  lightness: 0.126123
  brandStrength: 0.1302058
  rhythmicContrast: 0.5133562
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: episteme
